// P0 hardening for the current prototype: locked formula snapshots,
// Jira period-scoped sync, Leader criteria consistency and workflow guards.
const currentCriteriaFor=criteriaFor;
criteriaFor=function(group){const snapshot=typeof periodSnapshot==='function'?periodSnapshot():null;return currentStatus()==='locked'&&snapshot?.criteria?.[group]?snapshot.criteria[group]:currentCriteriaFor(group)};
createPeriodSnapshot=function(){const criteria=Object.fromEntries(Object.keys(groups).map(group=>[group,(customCriteria[group]||groups[group].criteria).map(c=>[c[0],Number(c[1])])]));const snapshot={version:2,period:period.value,createdAt:new Date().toISOString(),status:'locked',criteria,data:JSON.parse(JSON.stringify(state))};localStorage.setItem(snapshotKey(),JSON.stringify(snapshot));return snapshot};
const currentResult=result;
result=function(member,forceGroup){if(forceGroup===undefined&&selectedGroup==='Tất cả'&&member.leader)return currentResult(member,'Leader');return currentResult(member,forceGroup)};
const currentDashboard=renderDashboard;
renderDashboard=function(){currentDashboard();const root=document.querySelector('#dashboardRoot');if(!root)return;root.querySelectorAll('.data-quality-panel,.data-quality-inline').forEach(node=>node.remove());const q=dataQuality();const evidenceMissing=members.filter(member=>{const group=evalGroup(member),record=state[member.id]?.[group];return !record?.taskLinks||!Object.values(record.taskLinks).some(value=>Array.isArray(value)&&value.length)}).length;root.insertAdjacentHTML('beforeend',`<div class="data-quality-inline"><b>Chất lượng dữ liệu</b><span class="${q.unmapped?'quality-warn':'quality-good'}">Task chưa map: ${q.unmapped}</span><span class="${q.missingWorkload?'quality-warn':'quality-good'}">Member thiếu workload: ${q.missingWorkload}</span><span class="${evidenceMissing?'quality-warn':'quality-good'}">Member thiếu minh chứng: ${evidenceMissing}</span><span class="${q.invalidCriteria?'quality-warn':'quality-good'}">Bộ tiêu chí sai tổng: ${q.invalidCriteria}</span></div>`) };
function periodJql(){const settings=JSON.parse(localStorage.getItem('backend-jira-settings')||'{}'),parts=[],project=(settings.projectKey||'').trim();if(project)parts.push(`project = "${project.replace(/"/g,'\\"')}"`);const [year,month]=period.value.split('-').map(Number),next=new Date(year,month,1).toISOString().slice(0,10);parts.push(`created >= "${period.value}-01"`,`created < "${next}"`,'ORDER BY created DESC');return parts.join(' AND ')}
syncRealJiraFromBackend=async function(){const base=(localStorage.getItem('backend-kpi-api-base')||'http://localhost:8788').replace(/\/$/,''),button=document.querySelector('#syncRealJira');if(button){button.disabled=true;button.textContent='Đang đồng bộ...'}try{const query=new URLSearchParams({maxResults:'100',maxIssues:'1000',jql:periodJql()}),response=await fetch(`${base}/api/sync?${query}`),data=await response.json();if(!response.ok||data.error)throw new Error(data.error||'Backend không phản hồi');state.jiraIssues=data.issues||[];let mapped=0;members.forEach(member=>{const matched=state.jiraIssues.filter(task=>personKey(task.member)===personKey(member.name)||task.accountId===member.id);if(!matched.length)return;mapped+=matched.length;const committed=matched.length,closed=matched.filter(task=>task.done).length,committedPoints=matched.reduce((sum,task)=>sum+task.storyPoints,0),deliveredPoints=matched.filter(task=>task.done).reduce((sum,task)=>sum+task.storyPoints,0),rate=committed?closed/committed:0,group=evalGroup(member),criteria=criteriaFor(group);state[member.id]??={};state[member.id].workload={committed,closed,committedPoints,deliveredPoints};state[member.id][group]??={};state[member.id][group].scores??=[];if(criteria.length){const max=criteria[0][1];state[member.id][group].scores[0]=rate>=.9?max:rate>=.75?max*.6:rate>=.6?max*.267:0}state[member.id][group].taskLinks??={};state[member.id][group].taskLinks[0]=matched.map(task=>task.key)});save(`Đồng bộ ${state.jiraIssues.length} task Jira`);render();toast(`Đã sync ${state.jiraIssues.length} task · map ${mapped} task · ${data.pages||1} trang`)}catch(error){toast(`Không đồng bộ được Jira: ${error.message}`)}finally{if(button){button.disabled=false;button.textContent='Đồng bộ Jira Data Center'}}};
const currentRender=render;
render=function(){currentRender();const button=document.querySelector('#completeEvaluation');if(button){button.onclick=()=>{if(currentStatus()!=='draft'){toast('Chỉ đánh giá ở trạng thái Nháp mới được hoàn tất');return}localStorage.setItem(statusKey(),'submitted');save('Hoàn tất đánh giá');render()}}};
render();
